name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 1.1.2
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  js: ^0.6.1
  node_interop: ^1.0.0-dev.11.0
  meta: ^1.0.5
  quiver_hashcode: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0
  build_test:
